"""。。。

Revision ID: 0fe93b51adf8
Revises: ceb85bd58835
Create Date: 2025-12-10 20:47:23.828169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fe93b51adf8'
down_revision = 'ceb85bd58835'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uix_user_book_status'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrow_records', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uix_user_book_status'), ['user_id', 'book_id', 'status'])

    # ### end Alembic commands ###
